drone_id: 0

flight_params:
  gcs_failsafe_s: 5  # last gcs heartbeat > "gcs_failsafe_s" triggers failsafe state
  failsafe_watchdog_hz: 2.0

  alt_timeout_watchdog_hz: 10.0       # how often to check for operator inactivity for entering AltHold
  vz_override_timeout_s: 1.0          # how long to wait for operator inactivity before entering AltHold
  alt_ctrl_setpoint_hz: 20.0          # how often guided velocity setpoints are sent to FCU
  cmd_stale_timeout_s: 0.5            
  alt_ctrl_min_agl_m: 2.0

  takeoff_m: 2.0
  takeoff_reach_threshold_m:  0.20   # ±tolerance to consider takeoff altitude reached (m)
  takeoff_timeout_s:          10.0   # hard cap on takeoff monitor (s)
  
  logs_path: "/home/batuhan/shared/recordings"

altitude_controller:
  kp: 0.7
  ki: 0.0001
  kd: 0.3
  d_lpf_tau_s: 0.1
  output_min: -1.5
  output_max:  1.5
  integral_min: -0.1
  integral_max:  0.1

camera:
  device_path: "/dev/video0"
  width: 640
  height: 480
  fps: 30
  camera_mount_angle: 5.0     # degrees, positive downwards
  use_gimbal: true            # true if camera is mounted on gimbal: roll and pitch values do not change
  reverse_mounted: false      # whether the camera is mounted in reverse orientation (upside down)
  

vision_pipeline:
  obj_det_hef_path: /person_detector.hef # default path: "/usr/share/hailo-models/yolov8s_h8l.hef"
  obj_det_score_thresh: 0.5
  obj_det_model_input_size: 640   # square input side (px)
  obj_det_person_class_idx: 0     # person class index

  use_mcu_height_estimate: true
  
  camera_intrinsics:
    fx: 628.5174089378104
    fy: 626.7246596297234
    cx: 326.54433867625056
    cy: 248.53088818750663
 
  distortion:
    k1:  0.028448533103527362
    k2: -0.15787637678468983
    p1:  0.0009147754450880819
    p2:  0.0028768249435391887
    k3:  0.01782338771345667

custom_topics:
  mcu_bridge: /mcu_bridge/vertical_estimate
  images: "camera/image/compressed"
  autonomous_action: "/autonomous/action"
  manual_action:  "/teleop/action"
  manual_command: "/teleop/command" 
  alt_ctrl_input:    /altitude_controller/input    # control_gate → PID node
  alt_ctrl_output:   /altitude_controller/output   # PID node → control_gate

mavros_topics:
    state: "/mavros/state"
    battery: "/mavros/battery"
    extended_state: "/mavros/extended_state"
    statustext: "/mavros/statustext/recv"
    odom: "/mavros/local_position/odom"
    gps1_raw: "/mavros/gpsstatus/gps1/raw"

panel:
  refresh_hz: 10.0
  queue_size: 10
  stale_threshold_s: 5.0

  
teleop:
  hz: 8.0
  keyboard_devices: ["/dev/input/by-id/usb-Razer_Razer_Ornata_V3-event-kbd",
                     "/dev/input/by-id/usb-ASUSTek_Computer_Inc._N-KEY_Device-event-mouse"]

  velocity:
    horizontal_default: 1       # m/s
    vertical_default: 0.5       # m/s
    horizontal_increment: 1.0   # m/s per command
    vertical_increment: 0.5     # m/s per command
    horizontal_max: 5.0         # m/s
    vertical_max: 2.0           # m/s
    horizontal_min: 1.0        # m/s
    vertical_min: 0.5          # m/s

  yaw_rate:
    default: 0.5   # rad/s
    min: 0.1
    max: 1.0
    increment: 0.1  # rad/s per command
  
  commands:
    params:
      KILL_SWITCH:
        activation_time_s: 0.1
        latch: true
        kill_window_s: 2.0
      KILL_CONFIRM:
        activation_time_s: 0.0
        latch: true
      CONTROL_TOGGLE:
        activation_time_s: 0.25
        latch: true
      KEYBOARD_TOGGLE:
        activation_time_s: 0.25
        latch: true
      ARM:
        activation_time_s: 0.5
        latch: true
      DISARM:
        activation_time_s: 2.0
        latch: true
      LAND:
        activation_time_s: 0.5
        latch: true
      RTL:
        activation_time_s: 0.5
        latch: true
      TAKEOFF:
        activation_time_s: 1.0
        latch: true
      GUIDED:
        activation_time_s: 0.1
        latch: true
      SPEED_UP_HORIZONTAL:
        latch: true
        activation_time_s: 0.1
      SPEED_DOWN_HORIZONTAL:
        latch: true
        activation_time_s: 0.1
      SPEED_UP_VERTICAL:
        latch: true
        activation_time_s: 0.1
      SPEED_DOWN_VERTICAL:
        latch: true
        activation_time_s: 0.1
      SPEED_UP_YAW:
        latch: true
        activation_time_s: 0.1
      SPEED_DOWN_YAW:
        latch: true
        activation_time_s: 0.1
      VEL_YAW:
        activation_time_s: 0.0
        latch: false
      PRESS_SAFETY_SWITCH:
        activation_time_s: 1.0
        latch: true
      RECORD_VIDEO_TOGGLE:
        activation_time_s: 0.0
        latch: true
      STREAM_TOGGLE:
        activation_time_s: 0.0
        latch: true
      ALT_SUPPORT_TOGGLE:
        latch: true
        activation_time_s: 0.3
