drone_id: 0

flight_params:
  takeoff_m: 2.0
  gcs_failsafe_s: 10  # last gcs heartbeat > "gcs_failsafe_s" triggers failsafe state
  failsafe_watchdog_hz: 1.0
  logs_path: "/home/batuhan/shared/recordings"


camera:
  device_path: "/dev/video0"
  width: 800
  height: 600
  fps: 30
  

custom_topics:
  images: "camera/image/compressed"
  autonomous_action: "/autonomous/action"
  manual_action:  "/teleop/action"
  manual_command: "/teleop/command" 

mavros_topics:
    state: "/mavros/state"
    battery: "/mavros/battery"
    extended_state: "/mavros/extended_state"
    statustext: "/mavros/statustext/recv"
    odom: "/mavros/local_position/odom"
    gps1_raw: "/mavros/gpsstatus/gps1/raw"

panel:
  refresh_hz: 4.0
  queue_size: 10
  stale_threshold_s: 5.0

  
teleop:
  hz: 8.0
  keyboard_devices: ["/dev/input/by-id/usb-Razer_Razer_Ornata_V3-event-kbd",
                     "/dev/input/by-id/usb-ASUSTek_Computer_Inc._N-KEY_Device-event-mouse"]

  velocity:
    categories:
      horizontal: [2.0, 3.0, 5.0, 10.0]
      vertical:   [0.5, 1.0, 2.0, 3.0]
      default_start_index: 0     # e.g. horizontal vel: horizontal[default_start_index]

    yaw_rate: 0.6   # rad/s
  
  commands:
    params:
      KILL_SWITCH:
        activation_time_s: 1.0
        latch: true
        kill_window_s: 2.0
      KILL_CONFIRM:
        activation_time_s: 0.0
        latch: true
      CONTROL_TOGGLE:
        activation_time_s: 0.25
        latch: true
      KEYBOARD_TOGGLE:
        activation_time_s: 0.25
        latch: true
      ARM:
        activation_time_s: 1.0
        latch: true
      DISARM:
        activation_time_s: 2.0
        latch: true
      LAND:
        activation_time_s: 0.5
        latch: true
      RTL:
        activation_time_s: 0.5
        latch: true
      TAKEOFF:
        activation_time_s: 1.0
        latch: true
      GUIDED:
        activation_time_s: 0.1
        latch: true
      SPEED_UP:
        activation_time_s: 0.0
        latch: true
      SPEED_DOWN:
        activation_time_s: 0.0
        latch: true
      VEL_YAW:
        activation_time_s: 0.0
        latch: false
      PRESS_SAFETY_SWITCH:
        activation_time_s: 1.0
        latch: true
      SAVE_VIDEO_TOGGLE:
        activation_time_s: 0.0
        latch: true
