# Constants
int8 KILL_SWITCH            = 1
int8 KILL_CONFIRM           = 2
int8 CONTROL_TOGGLE         = 3
int8 KEYBOARD_TOGGLE        = 4
int8 ARM                    = 5
int8 DISARM                 = 6
int8 LAND                   = 7
int8 RTL                    = 8
int8 GUIDED                 = 9
int8 TAKEOFF                = 10
int8 PRESS_SAFETY_SWITCH    = 11
int8 SPEED_UP_HORIZONTAL    = 12
int8 SPEED_DOWN_HORIZONTAL  = 13
int8 SPEED_UP_VERTICAL      = 14
int8 SPEED_DOWN_VERTICAL    = 15
int8 SPEED_UP_YAW           = 16
int8 SPEED_DOWN_YAW         = 17
uint8 ALT_SUPPORT_TOGGLE    = 20
int8 VEL_YAW=100
int8 HOVER=101

# Fields
builtin_interfaces/Time stamp
string source
int8 command_id
float32 float_1
float32 float_2
bool bool_1